"""Row → view projections — port of `apps/server/src/orchestrator/projection.ts`."""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import Any

from pydantic import Field

from ..core.models import CamelModel, ExpectedConcept, PrepResource
from ..core.skill_id import SkillId as SkillIdType

__all__ = ["OrchestratorQuestion", "PrepActionRowLike", "row_to_action", "row_to_question"]


class PrepActionRowLike(CamelModel):
    id: str
    skill_id: str
    priority: float
    reason: str
    action: str
    success_criteria: list[str]
    status: str
    severity: str
    created_at: str
    source_evidence_ids: list[str]
    #: v0.4: builtin + pack + plugin learning resources.
    resources: list[PrepResource]


class OrchestratorQuestion(CamelModel):
    """`Question` plus the engine's selection metadata."""

    id: str
    session_id: str
    skill_id: SkillIdType
    topic: str
    text: str
    sub_skills: list[SkillIdType]
    expected_concepts: list[ExpectedConcept]
    difficulty: str
    selection_reason: str | None = Field(default=None, json_schema_extra={"emit_null": True})
    selection_priority: float | None = None
    #: §9.2 engine factor breakdown (null for practice/follow-up questions).
    selection_factors: dict[str, float] | None = Field(
        default=None, json_schema_extra={"emit_null": True}
    )
    #: §9.1 follow-up linkage.
    follow_up_of: str | None = Field(default=None, json_schema_extra={"emit_null": True})
    follow_up_focus: str | None = Field(default=None, json_schema_extra={"emit_null": True})
    #: §9.1 mode payload (coding problem, design focus dimension).
    extra: dict[str, Any]
    #: v0.4: question-source attribution (null when generated by the interviewer).
    source: str | None = Field(default=None, json_schema_extra={"emit_null": True})
    created_at: str


def _parse_list(value: object) -> list[Any]:
    if isinstance(value, list):
        return list(value)
    text = str(value if value is not None else "[]")
    parsed = json.loads(text)
    return list(parsed) if isinstance(parsed, list) else []


def _parse_obj(value: object) -> dict[str, Any] | None:
    if value is None:
        return None
    if isinstance(value, Mapping):
        return dict(value)
    text = str(value)
    if text == "":
        return None
    parsed = json.loads(text)
    return dict(parsed) if isinstance(parsed, Mapping) else None


def row_to_action(row: Mapping[str, Any]) -> PrepActionRowLike:
    return PrepActionRowLike(
        id=str(row["id"]),
        skill_id=str(row["skill_id"]),
        priority=float(row["priority"]),
        reason=str(row["reason"]),
        action=str(row["action"]),
        success_criteria=[str(item) for item in _parse_list(row["success_criteria"])],
        status=str(row["status"]),
        severity=str(row.get("severity") or "medium"),
        created_at=str(row["created_at"]),
        source_evidence_ids=[str(item) for item in _parse_list(row["source_evidence_ids"])],
        resources=[
            item
            for item in (
                PrepResource.model_validate(entry) for entry in _parse_list(row.get("resources"))
            )
            if item is not None
        ],
    )


def row_to_question(row: Mapping[str, Any]) -> OrchestratorQuestion:
    factors = _parse_obj(row.get("selection_factors"))
    extra = _parse_obj(row.get("extra")) or {}
    return OrchestratorQuestion(
        id=str(row["id"]),
        session_id=str(row["session_id"]),
        skill_id=str(row["skill_id"]),
        topic=str(row["topic"]),
        text=str(row["text"]),
        sub_skills=[str(item) for item in _parse_list(row["sub_skills"])],
        expected_concepts=[
            ExpectedConcept.model_validate(item)
            for item in _parse_list(row["expected_concepts"])
        ],
        difficulty=str(row["difficulty"]),
        selection_reason=row.get("selection_reason"),
        selection_priority=(
            float(row["selection_priority"]) if row.get("selection_priority") is not None else None
        ),
        selection_factors=(
            {str(key): float(value) for key, value in factors.items()} if factors else None
        ),
        follow_up_of=row.get("follow_up_of"),
        follow_up_focus=row.get("follow_up_focus"),
        extra=extra,
        source=extra.get("source") if isinstance(extra.get("source"), str) else None,
        created_at=str(row["created_at"]),
    )
