"""AI runtime layer — the Python port of `packages/runtime`.

`AIRuntime` is the only thing the rest of the backend knows about a provider
(invariant #4). Providers come from `RUNTIME_KINDS` plus trusted local modules
named by `interview-os.runtimes.json`; `RuntimeManager` makes the active one
switchable at runtime.

`run_structured` (invariant #2) and the partial-JSON parser live here too,
because they are runtime-facing; the skill manifest and `SkillHost` wiring
belong to the skill layer.
"""

from .acp import (
    AcpAgentConfig,
    AcpClient,
    AcpClientOptions,
    AcpRuntime,
    AcpRuntimeOptions,
    acp_health_check,
    build_acp_child_env,
    extract_text,
    find_acp_executable,
    stop_reason_to_error,
    update_to_event,
)
from .claude import (
    CLAUDE_SETUP_MESSAGE,
    ClaudeCodeRuntime,
    ClaudeQuery,
    ClaudeRuntimeOptions,
    ClaudeSdk,
    ClaudeSdkMessage,
    ClaudeSdkModelInfo,
    ClaudeSdkOptions,
    RealClaudeSdk,
    build_claude_child_env,
    claude_health_check,
    find_claude_executable,
    get_claude_version,
)
from .codex import (
    APP_SERVER_NOTIFICATIONS,
    CLIENT_INFO,
    CODEX_SETUP_MESSAGE,
    PROCESS_REQUEST_TIMEOUT_MS,
    CodexExecAdapter,
    CodexExecEventParser,
    CodexExecOptions,
    CodexProcess,
    CodexProcessOptions,
    CodexProtocol,
    CodexRuntime,
    CodexRuntimeOptions,
    CodexSessionManager,
    CodexSessionManagerOptions,
    EventQueue,
    ParsedExecLine,
    build_child_env,
    codex_health_check,
    find_codex_executable,
    get_codex_version,
    parse_exec_line,
)
from .codex import (
    DEFAULT_TASK_TIMEOUT_MS as CODEX_DEFAULT_TASK_TIMEOUT_MS,
)
from .errors import RuntimeError, RuntimeErrorCode
from .interface import (
    MODEL_ID_REGEX,
    REASONING_EFFORTS,
    AgentEvent,
    AgentResult,
    AgentTask,
    AIRuntime,
    AIUsageEvent,
    AIUsageSink,
    JSONSchema,
    ModelInfo,
    ProgressCallback,
    ProgressUpdate,
    ReasoningEffort,
    RuntimeEvent,
    RuntimeKind,
    RuntimeMessage,
    RuntimeSession,
    RuntimeState,
    RuntimeStatus,
    SessionInput,
    TaskMode,
    validate_model_and_effort,
)
from .logger import Logger, LogLevel, NullLogger
from .manager import RuntimeFactory, RuntimeManager, RuntimeManagerOptions, create_runtime
from .mock import MockRuntime, MockRuntimeOptions, MockTaskFallback, MockTaskHandler
from .partial_json import extract_partial_string_field
from .process import (
    CliRunResult,
    ExecResult,
    LaunchSpec,
    ensure_dir,
    env_number,
    exec_file_safe,
    exit_status,
    launch_spec,
    node_executable,
    quote_windows_arg,
    run_cli,
    spawn_command,
    timeout_from_env,
)
from .providers import (
    DEFAULT_WORKSPACE_DIR,
    HEALTH_CHECKERS,
    RUNTIME_KINDS,
    LoadedProviders,
    RuntimeHealthChecker,
    RuntimeProviderSpec,
    all_runtime_kinds,
    health_checker_for,
    instantiate_provider,
    is_runtime_kind,
    load_runtime_providers,
    mock_delay_ms,
    register_runtime_provider,
    registered_runtime_providers,
    workspace_dir_for,
)
from .structured import (
    MAX_ATTEMPTS,
    RETRYABLE_CODES,
    SessionRef,
    StructuredOutputError,
    StructuredRuntimeError,
    StructuredTask,
    run_structured,
    to_strict_json_schema,
)

__all__ = [
    "AIRuntime",
    "AIUsageEvent",
    "AIUsageSink",
    "APP_SERVER_NOTIFICATIONS",
    "CLAUDE_SETUP_MESSAGE",
    "CLIENT_INFO",
    "CODEX_DEFAULT_TASK_TIMEOUT_MS",
    "CODEX_SETUP_MESSAGE",
    "DEFAULT_WORKSPACE_DIR",
    "HEALTH_CHECKERS",
    "MAX_ATTEMPTS",
    "MODEL_ID_REGEX",
    "PROCESS_REQUEST_TIMEOUT_MS",
    "REASONING_EFFORTS",
    "RETRYABLE_CODES",
    "RUNTIME_KINDS",
    "AcpAgentConfig",
    "AcpClient",
    "AcpClientOptions",
    "AcpRuntime",
    "AcpRuntimeOptions",
    "AgentEvent",
    "AgentResult",
    "AgentTask",
    "CliRunResult",
    "ClaudeCodeRuntime",
    "ClaudeQuery",
    "ClaudeRuntimeOptions",
    "ClaudeSdk",
    "ClaudeSdkMessage",
    "ClaudeSdkModelInfo",
    "ClaudeSdkOptions",
    "CodexExecAdapter",
    "CodexExecEventParser",
    "CodexExecOptions",
    "CodexProcess",
    "CodexProcessOptions",
    "CodexProtocol",
    "CodexRuntime",
    "CodexRuntimeOptions",
    "CodexSessionManager",
    "CodexSessionManagerOptions",
    "EventQueue",
    "ExecResult",
    "JSONSchema",
    "LaunchSpec",
    "LoadedProviders",
    "LogLevel",
    "Logger",
    "MockRuntime",
    "MockRuntimeOptions",
    "MockTaskFallback",
    "MockTaskHandler",
    "ModelInfo",
    "NullLogger",
    "ParsedExecLine",
    "ProgressCallback",
    "ProgressUpdate",
    "RealClaudeSdk",
    "ReasoningEffort",
    "RuntimeError",
    "RuntimeErrorCode",
    "RuntimeEvent",
    "RuntimeFactory",
    "RuntimeHealthChecker",
    "RuntimeKind",
    "RuntimeManager",
    "RuntimeManagerOptions",
    "RuntimeMessage",
    "RuntimeProviderSpec",
    "RuntimeSession",
    "RuntimeState",
    "RuntimeStatus",
    "SessionInput",
    "SessionRef",
    "StructuredOutputError",
    "StructuredRuntimeError",
    "StructuredTask",
    "TaskMode",
    "acp_health_check",
    "all_runtime_kinds",
    "build_acp_child_env",
    "build_child_env",
    "build_claude_child_env",
    "claude_health_check",
    "codex_health_check",
    "create_runtime",
    "ensure_dir",
    "env_number",
    "exec_file_safe",
    "exit_status",
    "extract_partial_string_field",
    "extract_text",
    "find_acp_executable",
    "find_claude_executable",
    "find_codex_executable",
    "get_claude_version",
    "get_codex_version",
    "health_checker_for",
    "instantiate_provider",
    "is_runtime_kind",
    "launch_spec",
    "load_runtime_providers",
    "mock_delay_ms",
    "node_executable",
    "parse_exec_line",
    "quote_windows_arg",
    "register_runtime_provider",
    "registered_runtime_providers",
    "run_cli",
    "run_structured",
    "spawn_command",
    "stop_reason_to_error",
    "timeout_from_env",
    "to_strict_json_schema",
    "update_to_event",
    "validate_model_and_effort",
    "workspace_dir_for",
]
