"""Core state shapes — the single source of truth for every model (invariant #1).

`interview_os.core.models` holds the Pydantic v2 port of `packages/core`'s Zod
schemas; `interview_os.core.plugin_api` holds the `PLUGIN_HOOKS` contracts; the
remaining modules hold the pure logic (readiness, gaps, prioritisation, state
machine, rounds, modes, taxonomy, voice, resources).
"""

from . import plugin_api
from .assessment import normalize_evaluation
from .gaps import TARGET_SCORE_BY_LEVEL, calculate_gaps
from .models import *  # noqa: F403
from .models import __all__ as _models_all
from .modes import (
    MIXED_MODE,
    FollowUpDecision,
    LoadedPluginMode,
    ModeAnswerField,
    ModeContextNeeds,
    ModeDefinition,
    ModePrompts,
    ModeQuestionContext,
    all_modes,
    generic_follow_up,
    get_mode,
    in_subtree,
    is_mode_available,
    is_mode_id,
    mode_plugin_id,
    register_plugin_modes,
    reset_plugin_modes,
    rubric_score,
    unregister_plugin_modes,
)
from .plugin_api import (
    CAPABILITY_HOOKS,
    LEGACY_HOOK_KIND,
    MANIFEST_FEATURE_SINCE,
    PLUGIN_API_VERSION,
    PLUGIN_EVENT_HOOKS,
    PLUGIN_EVENT_NAMES,
    PLUGIN_HOOK_NAMES,
    PLUGIN_HOOKS,
    HookSpec,
    capability_hooks,
    hook_capability,
    is_plugin_api_compatible,
    is_plugin_hook_name,
)
from .prioritize import (
    LoopWeakSkill,
    SelectionFactors,
    SelectNextSkillInput,
    SelectNextSkillResult,
    SkillCandidate,
    difficulty_for,
    select_next_skill,
)
from .readiness import (
    CONFIDENCE_CAP,
    EVIDENCE_HALF_LIFE_DAYS,
    EVIDENCE_TYPE_WEIGHT,
    RECENCY_DECAY,
    UNKNOWN_PRIOR,
    DirectReadiness,
    TaxonomyLike,
    build_readiness_graph,
    compute_skill_readiness,
    confidence_for_weight,
    status_for_score,
)
from .resources import builtin_resources_for, merge_resources
from .rounds import in_round, round_fallback_requirements
from .skill_id import (
    SKILL_ID_REGEX,
    SkillId,
    humanize_skill_segment,
    is_skill_id,
    parent_skill_id,
)
from .state_machine import (
    TRANSITIONS,
    InvalidTransitionError,
    can_transition,
    next_events,
    transition,
)
from .taxonomy import (
    EXTRA_ALIASES,
    RELATED_EDGES,
    TAXONOMY_SEED,
    SkillMatch,
    TaxonomyNode,
    all_nodes,
    ancestors,
    children_of,
    get_node,
    has_node,
    label_for,
    match_skills,
    normalize_skill_id,
    parent_of,
    register_nodes,
    related_to,
)
from .voice import count_fillers, voice_feedback

__all__ = [
    "CAPABILITY_HOOKS",
    "LEGACY_HOOK_KIND",
    "MANIFEST_FEATURE_SINCE",
    "PLUGIN_API_VERSION",
    "PLUGIN_EVENT_HOOKS",
    "PLUGIN_EVENT_NAMES",
    "PLUGIN_HOOK_NAMES",
    "PLUGIN_HOOKS",
    "SKILL_ID_REGEX",
    "HookSpec",
    "SkillId",
    "capability_hooks",
    "hook_capability",
    "humanize_skill_segment",
    "is_plugin_hook_name",
    "is_plugin_api_compatible",
    "is_skill_id",
    "parent_skill_id",
    "plugin_api",
    *_models_all,
    # pure logic
    "CONFIDENCE_CAP",
    "EVIDENCE_HALF_LIFE_DAYS",
    "EVIDENCE_TYPE_WEIGHT",
    "EXTRA_ALIASES",
    "MIXED_MODE",
    "RECENCY_DECAY",
    "RELATED_EDGES",
    "TARGET_SCORE_BY_LEVEL",
    "TAXONOMY_SEED",
    "TRANSITIONS",
    "UNKNOWN_PRIOR",
    "DirectReadiness",
    "FollowUpDecision",
    "InvalidTransitionError",
    "LoadedPluginMode",
    "LoopWeakSkill",
    "ModeAnswerField",
    "ModeContextNeeds",
    "ModeDefinition",
    "ModePrompts",
    "ModeQuestionContext",
    "SelectNextSkillInput",
    "SelectNextSkillResult",
    "SelectionFactors",
    "SkillCandidate",
    "SkillMatch",
    "TaxonomyLike",
    "TaxonomyNode",
    "all_modes",
    "all_nodes",
    "ancestors",
    "build_readiness_graph",
    "builtin_resources_for",
    "calculate_gaps",
    "can_transition",
    "children_of",
    "compute_skill_readiness",
    "confidence_for_weight",
    "count_fillers",
    "difficulty_for",
    "generic_follow_up",
    "get_mode",
    "get_node",
    "has_node",
    "in_round",
    "in_subtree",
    "is_mode_available",
    "is_mode_id",
    "label_for",
    "match_skills",
    "merge_resources",
    "mode_plugin_id",
    "next_events",
    "normalize_skill_id",
    "normalize_evaluation",
    "parent_of",
    "register_nodes",
    "register_plugin_modes",
    "related_to",
    "reset_plugin_modes",
    "round_fallback_requirements",
    "rubric_score",
    "select_next_skill",
    "status_for_score",
    "transition",
    "unregister_plugin_modes",
    "voice_feedback",
]
