"""Taxonomy seed data — port of `taxonomy/seed.ts` (same ids, labels, keywords)."""

from __future__ import annotations

from dataclasses import dataclass, field

from .skill_id import SkillId

__all__ = ["TAXONOMY_SEED", "TaxonomyNodeSeed"]


@dataclass(frozen=True, slots=True)
class TaxonomyNodeSeed:
    id: SkillId
    label: str
    keywords: list[str] = field(default_factory=list)


TAXONOMY_SEED: list[TaxonomyNodeSeed] = [
    TaxonomyNodeSeed(
        id="python",
        label="Python",
        keywords=["python", "python3", "pandas", "numpy", "django", "flask", "fastapi"],
    ),
    TaxonomyNodeSeed(
        id="apis",
        label="APIs",
        keywords=["api", "apis", "endpoint", "endpoints", "http", "openapi"],
    ),
    TaxonomyNodeSeed(
        id="apis.rest",
        label="REST APIs",
        keywords=["rest", "restful", "rest api", "resource", "idempotent", "status code"],
    ),
    TaxonomyNodeSeed(
        id="sql",
        label="SQL",
        keywords=[
            "sql",
            "postgres",
            "postgresql",
            "mysql",
            "sqlite",
            "relational",
            "query",
            "queries",
        ],
    ),
    TaxonomyNodeSeed(
        id="sql.query-optimization",
        label="SQL Query Optimization",
        keywords=["query optimization", "explain plan", "query plan", "slow query", "n+1"],
    ),
    TaxonomyNodeSeed(
        id="sql.indexing",
        label="SQL Indexing",
        keywords=["index", "indexes", "indexing", "b-tree", "composite index", "covering index"],
    ),
    TaxonomyNodeSeed(
        id="sql.transactions",
        label="SQL Transactions",
        keywords=[
            "transaction",
            "transactions",
            "acid",
            "isolation level",
            "rollback",
            "deadlock",
            "optimistic locking",
            "serializable",
        ],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems",
        label="Distributed Systems",
        keywords=["distributed system", "distributed-systems", "microservices", "distributed"],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems.caching",
        label="Caching",
        keywords=["cache", "caching", "cached", "redis", "memcached", "cdn"],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems.caching.cache-strategies",
        label="Cache Strategies",
        keywords=[
            "cache-aside",
            "write-through",
            "write-behind",
            "read-through",
            "ttl",
            "time-to-live",
            "refresh-ahead",
        ],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems.caching.cache-invalidation",
        label="Cache Invalidation",
        keywords=[
            "invalidation",
            "invalidate",
            "invalidates",
            "stale",
            "staleness",
            "eviction",
            "evict",
            "purge",
            "expire",
            "expiration",
        ],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems.message-queues",
        label="Message Queues",
        keywords=[
            "message queue",
            "queue",
            "queues",
            "kafka",
            "rabbitmq",
            "sqs",
            "pub/sub",
            "pubsub",
            "consumer",
            "producer",
            "topic",
        ],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems.consistency",
        label="Consistency",
        keywords=[
            "consistency",
            "consistent",
            "eventual consistency",
            "strong consistency",
            "cap theorem",
            "quorum",
            "linearizable",
        ],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems.partitioning",
        label="Partitioning",
        keywords=[
            "partitioning",
            "partition",
            "partitions",
            "sharding",
            "shard",
            "shards",
            "consistent hashing",
            "hot partition",
        ],
    ),
    TaxonomyNodeSeed(
        id="distributed-systems.replication",
        label="Replication",
        keywords=[
            "replication",
            "replica",
            "replicas",
            "leader-follower",
            "leader election",
            "failover",
            "primary-replica",
        ],
    ),
    TaxonomyNodeSeed(
        id="system-design",
        label="System Design",
        keywords=["system design", "architecture", "design a", "high-level design"],
    ),
    TaxonomyNodeSeed(
        id="system-design.requirements-analysis",
        label="Requirements Analysis",
        keywords=[
            "functional requirements",
            "non-functional requirements",
            "requirements analysis",
            "clarifying questions",
            "scoping",
        ],
    ),
    TaxonomyNodeSeed(
        id="system-design.capacity-estimation",
        label="Capacity Estimation",
        keywords=[
            "capacity estimation",
            "back-of-envelope",
            "qps",
            "throughput",
            "storage estimate",
            "bandwidth",
            "estimation",
        ],
    ),
    TaxonomyNodeSeed(
        id="system-design.scalability",
        label="Scalability",
        keywords=[
            "scalability",
            "scale",
            "scaling",
            "horizontal scaling",
            "vertical scaling",
            "load balancer",
            "load balancing",
            "autoscaling",
        ],
    ),
    TaxonomyNodeSeed(
        id="system-design.reliability",
        label="Reliability",
        keywords=[
            "reliability",
            "availability",
            "fault tolerance",
            "fault-tolerant",
            "redundancy",
            "sla",
            "slo",
            "disaster recovery",
        ],
    ),
    TaxonomyNodeSeed(
        id="system-design.data-modeling",
        label="Data Modeling (Design)",
        keywords=[
            "data model",
            "data modeling",
            "entity",
            "entities",
            "schema design",
            "er diagram",
            "relational model",
        ],
    ),
    TaxonomyNodeSeed(
        id="system-design.async-processing",
        label="Async Processing",
        keywords=[
            "async processing",
            "asynchronous",
            "background job",
            "background jobs",
            "worker queue",
            "event-driven",
            "task queue",
        ],
    ),
    TaxonomyNodeSeed(
        id="coding",
        label="Coding & Algorithms",
        keywords=[
            "coding",
            "coding challenge",
            "algorithm",
            "algorithms",
            "live coding",
            "whiteboard",
            "leetcode",
        ],
    ),
    TaxonomyNodeSeed(
        id="coding.algorithms",
        label="Algorithms",
        keywords=[
            "algorithm",
            "algorithms",
            "two pointers",
            "sliding window",
            "binary search",
            "recursion",
            "dynamic programming",
            "bfs",
            "dfs",
            "sorting",
        ],
    ),
    TaxonomyNodeSeed(
        id="coding.data-structures",
        label="Data Structures",
        keywords=[
            "data structure",
            "data structures",
            "hash map",
            "hash table",
            "linked list",
            "binary tree",
            "heap",
            "trie",
            "stack",
            "deque",
        ],
    ),
    TaxonomyNodeSeed(
        id="coding.complexity",
        label="Complexity Analysis",
        keywords=[
            "big-o",
            "o(n",
            "time complexity",
            "space complexity",
            "complexity analysis",
            "runtime complexity",
        ],
    ),
    TaxonomyNodeSeed(
        id="coding.edge-cases",
        label="Edge Cases & Testing",
        keywords=[
            "edge case",
            "edge cases",
            "corner case",
            "boundary condition",
            "empty input",
            "off-by-one",
            "unit test",
            "unit tests",
            "test case",
        ],
    ),
    TaxonomyNodeSeed(
        id="coding.code-quality",
        label="Code Quality",
        keywords=[
            "clean code",
            "readable code",
            "code quality",
            "refactor",
            "refactoring",
            "naming",
            "modular",
        ],
    ),
    TaxonomyNodeSeed(
        id="hiring-manager",
        label="Hiring Manager",
        keywords=[
            "hiring manager",
            "skip level",
            "org design",
            "cross-team",
            "team strategy",
        ],
    ),
    TaxonomyNodeSeed(
        id="hiring-manager.role-fit",
        label="Role Fit",
        keywords=["why this team", "role fit", "fit for this role", "what attracts you"],
    ),
    TaxonomyNodeSeed(
        id="hiring-manager.scope-impact",
        label="Scope & Impact",
        keywords=[
            "scope and impact",
            "grew the scope",
            "influence without authority",
            "org-wide",
            "company-wide",
        ],
    ),
    TaxonomyNodeSeed(
        id="hiring-manager.prioritization",
        label="Prioritization Decisions",
        keywords=[
            "reprioritize",
            "reprioritized",
            "priority call",
            "what not to build",
            "ruthless prioritization",
            "roadmap trade",
        ],
    ),
    TaxonomyNodeSeed(
        id="hiring-manager.leadership-style",
        label="Leadership Style",
        keywords=[
            "leadership style",
            "manage up",
            "managing up",
            "grew engineers",
            "grew the team",
            "coached",
        ],
    ),
    TaxonomyNodeSeed(
        id="behavioral",
        label="Behavioral",
        keywords=["behavioral", "tell me about a time", "star", "soft skills"],
    ),
    TaxonomyNodeSeed(
        id="behavioral.leadership",
        label="Leadership",
        keywords=["leadership", "led", "mentored", "mentorship", "initiative", "influence"],
    ),
    TaxonomyNodeSeed(
        id="behavioral.conflict",
        label="Conflict",
        keywords=[
            "conflict",
            "disagreement",
            "disagreed",
            "difficult coworker",
            "pushback",
            "tension",
        ],
    ),
    TaxonomyNodeSeed(
        id="behavioral.ownership",
        label="Ownership",
        keywords=[
            "ownership",
            "took ownership",
            "accountability",
            "end-to-end",
            "drove",
            "saw it through",
        ],
    ),
    TaxonomyNodeSeed(
        id="behavioral.failure-learning",
        label="Learning from Failure",
        keywords=[
            "failure",
            "failed",
            "mistake",
            "postmortem",
            "post-mortem",
            "learned from",
            "retrospective",
            "went wrong",
        ],
    ),
    TaxonomyNodeSeed(
        id="behavioral.collaboration",
        label="Collaboration",
        keywords=[
            "collaboration",
            "collaborated",
            "cross-functional",
            "pairing",
            "teamwork",
            "worked closely with",
        ],
    ),
    TaxonomyNodeSeed(
        id="hr",
        label="HR & Motivation",
        keywords=["culture", "values", "motivation", "career goals", "work style", "why join"],
    ),
    TaxonomyNodeSeed(
        id="hr.motivation",
        label="Motivation",
        keywords=[
            "motivation",
            "motivated",
            "why this role",
            "why us",
            "why join",
            "excited about",
            "passion",
        ],
    ),
    TaxonomyNodeSeed(
        id="hr.career-goals",
        label="Career Goals",
        keywords=[
            "career goals",
            "career growth",
            "five years",
            "5 years",
            "growth path",
            "next step",
            "career direction",
        ],
    ),
    TaxonomyNodeSeed(
        id="hr.culture-fit",
        label="Culture Fit",
        keywords=["culture fit", "culture add", "team culture", "our values", "company values"],
    ),
    TaxonomyNodeSeed(
        id="hr.work-style",
        label="Work Style",
        keywords=[
            "work style",
            "working style",
            "remote",
            "autonomy",
            "feedback style",
            "how do you work",
        ],
    ),
    TaxonomyNodeSeed(
        id="communication",
        label="Communication",
        keywords=["communication", "communicate", "explaining", "presentation", "stakeholder"],
    ),
    TaxonomyNodeSeed(
        id="product",
        label="Product",
        keywords=["product", "product sense", "user research", "roadmap"],
    ),
    TaxonomyNodeSeed(
        id="product.metrics",
        label="Product Metrics",
        keywords=[
            "product metrics",
            "north star",
            "kpi",
            "kpis",
            "a/b test",
            "a/b testing",
            "experimentation",
            "retention",
            "activation",
            "funnel",
            "engagement metrics",
        ],
    ),
    TaxonomyNodeSeed(
        id="product.prioritization",
        label="Product Prioritization",
        keywords=["prioritization", "prioritize", "rice", "trade-off", "tradeoff", "mvp"],
    ),
    TaxonomyNodeSeed(
        id="data-engineering",
        label="Data Engineering",
        keywords=["data engineering", "data engineer", "big data", "data warehouse"],
    ),
    TaxonomyNodeSeed(
        id="data-engineering.pipelines",
        label="Data Pipelines",
        keywords=[
            "etl",
            "elt",
            "pipeline",
            "pipelines",
            "airflow",
            "dag",
            "spark",
            "batch processing",
        ],
    ),
    TaxonomyNodeSeed(
        id="data-engineering.modeling",
        label="Data Modeling",
        keywords=[
            "data modeling",
            "dimensional modeling",
            "star schema",
            "schema design",
            "warehouse",
            "fact table",
        ],
    ),
    TaxonomyNodeSeed(
        id="infrastructure",
        label="Infrastructure",
        keywords=["infrastructure", "devops", "platform engineering", "ci/cd"],
    ),
    TaxonomyNodeSeed(
        id="infrastructure.kubernetes",
        label="Kubernetes",
        keywords=["kubernetes", "k8s", "container orchestration", "helm", "docker"],
    ),
    TaxonomyNodeSeed(
        id="infrastructure.observability",
        label="Observability",
        keywords=[
            "observability",
            "monitoring",
            "tracing",
            "prometheus",
            "grafana",
            "opentelemetry",
            "instrumentation",
        ],
    ),
]
