import type { SkillId } from "../skill-id.js";

export interface TaxonomyNodeSeed {
  id: SkillId;
  label: string;
  keywords: string[];
}

export const TAXONOMY_SEED: TaxonomyNodeSeed[] = [
  {
    id: "python",
    label: "Python",
    keywords: ["python", "python3", "pandas", "numpy", "django", "flask", "fastapi"],
  },
  {
    id: "apis",
    label: "APIs",
    keywords: ["api", "apis", "endpoint", "endpoints", "http", "openapi"],
  },
  {
    id: "apis.rest",
    label: "REST APIs",
    keywords: ["rest", "restful", "rest api", "resource", "idempotent", "status code"],
  },
  {
    id: "sql",
    label: "SQL",
    keywords: ["sql", "postgres", "postgresql", "mysql", "sqlite", "relational", "query", "queries"],
  },
  {
    id: "sql.query-optimization",
    label: "SQL Query Optimization",
    keywords: ["query optimization", "explain plan", "query plan", "slow query", "n+1"],
  },
  {
    id: "sql.indexing",
    label: "SQL Indexing",
    keywords: ["index", "indexes", "indexing", "b-tree", "composite index", "covering index"],
  },
  {
    id: "distributed-systems",
    label: "Distributed Systems",
    keywords: ["distributed system", "distributed-systems", "microservices", "distributed"],
  },
  {
    id: "distributed-systems.caching",
    label: "Caching",
    keywords: ["cache", "caching", "cached", "redis", "memcached", "cdn"],
  },
  {
    id: "distributed-systems.caching.cache-strategies",
    label: "Cache Strategies",
    keywords: [
      "cache-aside",
      "write-through",
      "write-behind",
      "read-through",
      "ttl",
      "time-to-live",
      "refresh-ahead",
    ],
  },
  {
    id: "distributed-systems.caching.cache-invalidation",
    label: "Cache Invalidation",
    keywords: [
      "invalidation",
      "invalidate",
      "invalidates",
      "stale",
      "staleness",
      "eviction",
      "evict",
      "purge",
      "expire",
      "expiration",
    ],
  },
  {
    id: "distributed-systems.message-queues",
    label: "Message Queues",
    keywords: [
      "message queue",
      "queue",
      "queues",
      "kafka",
      "rabbitmq",
      "sqs",
      "pub/sub",
      "pubsub",
      "consumer",
      "producer",
      "topic",
    ],
  },
  {
    id: "distributed-systems.consistency",
    label: "Consistency",
    keywords: [
      "consistency",
      "consistent",
      "eventual consistency",
      "strong consistency",
      "cap theorem",
      "quorum",
      "linearizable",
    ],
  },
  {
    id: "distributed-systems.partitioning",
    label: "Partitioning",
    keywords: [
      "partitioning",
      "partition",
      "partitions",
      "sharding",
      "shard",
      "shards",
      "consistent hashing",
      "hot partition",
    ],
  },
  {
    id: "distributed-systems.replication",
    label: "Replication",
    keywords: [
      "replication",
      "replica",
      "replicas",
      "leader-follower",
      "leader election",
      "failover",
      "primary-replica",
    ],
  },
  {
    id: "system-design",
    label: "System Design",
    keywords: ["system design", "architecture", "design a", "high-level design"],
  },
  {
    id: "system-design.requirements-analysis",
    label: "Requirements Analysis",
    keywords: [
      "functional requirements",
      "non-functional requirements",
      "requirements analysis",
      "clarifying questions",
      "scoping",
    ],
  },
  {
    id: "system-design.capacity-estimation",
    label: "Capacity Estimation",
    keywords: [
      "capacity estimation",
      "back-of-envelope",
      "qps",
      "throughput",
      "storage estimate",
      "bandwidth",
      "estimation",
    ],
  },
  {
    id: "system-design.scalability",
    label: "Scalability",
    keywords: [
      "scalability",
      "scale",
      "scaling",
      "horizontal scaling",
      "vertical scaling",
      "load balancer",
      "load balancing",
      "autoscaling",
    ],
  },
  {
    id: "system-design.reliability",
    label: "Reliability",
    keywords: [
      "reliability",
      "availability",
      "fault tolerance",
      "fault-tolerant",
      "redundancy",
      "sla",
      "slo",
      "disaster recovery",
    ],
  },
  {
    id: "behavioral",
    label: "Behavioral",
    keywords: ["behavioral", "tell me about a time", "star", "soft skills"],
  },
  {
    id: "behavioral.leadership",
    label: "Leadership",
    keywords: ["leadership", "led", "mentored", "mentorship", "initiative", "influence"],
  },
  {
    id: "behavioral.conflict",
    label: "Conflict",
    keywords: ["conflict", "disagreement", "disagreed", "difficult coworker", "pushback", "tension"],
  },
  {
    id: "behavioral.ownership",
    label: "Ownership",
    keywords: [
      "ownership",
      "took ownership",
      "accountability",
      "end-to-end",
      "drove",
      "saw it through",
    ],
  },
  {
    id: "behavioral.failure-learning",
    label: "Learning from Failure",
    keywords: [
      "failure",
      "failed",
      "mistake",
      "postmortem",
      "post-mortem",
      "learned from",
      "retrospective",
      "went wrong",
    ],
  },
  {
    id: "behavioral.collaboration",
    label: "Collaboration",
    keywords: [
      "collaboration",
      "collaborated",
      "cross-functional",
      "pairing",
      "teamwork",
      "worked closely with",
    ],
  },
  {
    id: "hr",
    label: "HR & Motivation",
    keywords: ["culture", "values", "motivation", "career goals", "work style", "why join"],
  },
  {
    id: "hr.motivation",
    label: "Motivation",
    keywords: [
      "motivation",
      "motivated",
      "why this role",
      "why us",
      "why join",
      "excited about",
      "passion",
    ],
  },
  {
    id: "hr.career-goals",
    label: "Career Goals",
    keywords: [
      "career goals",
      "career growth",
      "five years",
      "5 years",
      "growth path",
      "next step",
      "career direction",
    ],
  },
  {
    id: "hr.culture-fit",
    label: "Culture Fit",
    keywords: ["culture fit", "culture add", "team culture", "our values", "company values"],
  },
  {
    id: "hr.work-style",
    label: "Work Style",
    keywords: [
      "work style",
      "working style",
      "remote",
      "autonomy",
      "feedback style",
      "how do you work",
    ],
  },
  {
    id: "communication",
    label: "Communication",
    keywords: ["communication", "communicate", "explaining", "presentation", "stakeholder"],
  },
  {
    id: "product",
    label: "Product",
    keywords: ["product", "product sense", "user research", "roadmap"],
  },
  {
    id: "product.metrics",
    label: "Product Metrics",
    keywords: [
      "product metrics",
      "north star",
      "kpi",
      "kpis",
      "a/b test",
      "a/b testing",
      "experimentation",
      "retention",
      "activation",
      "funnel",
      "engagement metrics",
    ],
  },
  {
    id: "product.prioritization",
    label: "Product Prioritization",
    keywords: ["prioritization", "prioritize", "rice", "trade-off", "tradeoff", "mvp"],
  },
  {
    id: "data-engineering",
    label: "Data Engineering",
    keywords: ["data engineering", "data engineer", "big data", "data warehouse"],
  },
  {
    id: "data-engineering.pipelines",
    label: "Data Pipelines",
    keywords: ["etl", "elt", "pipeline", "pipelines", "airflow", "dag", "spark", "batch processing"],
  },
  {
    id: "data-engineering.modeling",
    label: "Data Modeling",
    keywords: [
      "data modeling",
      "dimensional modeling",
      "star schema",
      "schema design",
      "warehouse",
      "fact table",
    ],
  },
  {
    id: "infrastructure",
    label: "Infrastructure",
    keywords: ["infrastructure", "devops", "platform engineering", "ci/cd"],
  },
  {
    id: "infrastructure.kubernetes",
    label: "Kubernetes",
    keywords: ["kubernetes", "k8s", "container orchestration", "helm", "docker"],
  },
  {
    id: "infrastructure.observability",
    label: "Observability",
    keywords: [
      "observability",
      "monitoring",
      "tracing",
      "prometheus",
      "grafana",
      "opentelemetry",
      "instrumentation",
    ],
  },
];
