"""Generate TypeScript model types from the FastAPI schema export.

Reads `apps/api/schema/*.json` (the Pydantic JSON-Schema export, one file per
group) and writes a single TS module of `export interface` / `export type`
declarations. This is the frontend's replacement for the hand-written
`packages/core` model types at cut-over (design §13.1).

Run:  uv run python scripts/generate_ts_types.py <out.ts>
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

SCHEMA_DIR = Path(__file__).resolve().parent.parent / "schema"

_PRIMITIVES = {"string": "string", "number": "number", "integer": "number", "boolean": "boolean"}

_IDENTIFIER_RE = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


def _key(name: str) -> str:
    return name if _IDENTIFIER_RE.match(name) else json.dumps(name)


class Generator:
    def __init__(self) -> None:
        self.emitted: dict[str, str] = {}
        self.order: list[str] = []

    def type_expr(self, node: Any) -> str:
        if node is True or node == {}:
            return "unknown"
        if not isinstance(node, dict):
            return "unknown"
        if "const" in node:
            return json.dumps(node["const"])
        enum = node.get("enum")
        if isinstance(enum, list):
            return " | ".join(json.dumps(value) for value in enum)
        if "anyOf" in node:
            return self._union([self.type_expr(item) for item in node["anyOf"]])
        if "oneOf" in node:
            return self._union([self.type_expr(item) for item in node["oneOf"]])
        if "allOf" in node:
            parts = [self.type_expr(item) for item in node["allOf"]]
            return " & ".join(dict.fromkeys(parts))
        ref = node.get("$ref")
        if isinstance(ref, str):
            return ref.rsplit("/", 1)[-1]
        node_type = node.get("type")
        if isinstance(node_type, list):
            return self._union([self.type_expr({**node, "type": item}) for item in node_type])
        if node_type == "null":
            return "null"
        if node_type == "array":
            items = self.type_expr(node.get("items", {}))
            if "|" in items and not items.startswith("("):
                items = f"({items})"
            return f"{items}[]"
        if node_type == "object" or "properties" in node:
            return self._object(node)
        if node_type in _PRIMITIVES:
            return _PRIMITIVES[node_type]
        return "unknown"

    def _object(self, node: dict[str, Any]) -> str:
        props = node.get("properties")
        if not props:
            extra = node.get("additionalProperties")
            if isinstance(extra, dict):
                return f"Record<string, {self.type_expr(extra)}>"
            return "Record<string, unknown>"
        required = set(node.get("required", []))
        fields = [
            f"{_key(key)}{'' if key in required else '?'}: {self.type_expr(value)}"
            for key, value in props.items()
        ]
        return "{ " + "; ".join(fields) + " }"

    @staticmethod
    def _union(parts: list[str]) -> str:
        seen: list[str] = []
        for part in parts:
            if part not in seen:
                seen.append(part)
        return " | ".join(seen) if seen else "unknown"

    def hoist_defs(self, defs: Any) -> None:
        if not isinstance(defs, dict):
            return
        for name, schema in defs.items():
            self.declare(name, schema)

    def declare(self, name: str, schema: Any) -> None:
        if name in self.emitted:
            return
        if isinstance(schema, dict):
            self.hoist_defs(schema.get("$defs"))
            expr = self.type_expr(schema)
            defs = schema.get("$defs")
            if expr == name and isinstance(defs, dict) and name in defs:
                expr = self.type_expr(defs[name])
            if expr == name:
                expr = "Record<string, unknown>"
        else:
            expr = "unknown"
        self.emitted[name] = expr
        self.order.append(name)


def main() -> int:
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else (SCHEMA_DIR.parent / "generated.ts")
    generator = Generator()
    for path in sorted(SCHEMA_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        models = data.get("models", {})
        for name, schema in models.items():
            generator.declare(name, schema)

    lines = [
        "/* AUTO-GENERATED by apps/api/scripts/generate_ts_types.py — do not edit. */",
        "",
        "/* eslint-disable */",
        "",
    ]
    for name in dict.fromkeys(generator.order):
        expr = generator.emitted[name]
        keyword = "interface" if expr.startswith("{ ") and "|" not in expr else "type"
        if keyword == "interface":
            body = expr[2:-2]
            lines.append(f"export interface {name} {{ {body} }}")
        else:
            lines.append(f"export type {name} = {expr};")
        lines.append("")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out} ({len(generator.order)} types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
