import type { PrepResource, Question, QuestionCandidate, SkillId } from "@interview-os/core";

export interface PrepActionRowLike {
  id: string;
  skillId: string;
  priority: number;
  reason: string;
  action: string;
  successCriteria: string[];
  status: string;
  severity: string;
  createdAt: string;
  sourceEvidenceIds: string[];
  /** v0.4: builtin + pack + plugin learning resources. */
  resources: PrepResource[];
}

export type OrchestratorQuestion = Omit<Question, "followUpOf"> & {
  selectionReason: string | null;
  selectionPriority: number | null;
  /** §9.2 engine factor breakdown (null for practice/follow-up questions). */
  selectionFactors: Record<string, number> | null;
  /** §9.1 follow-up linkage. */
  followUpOf: string | null;
  followUpFocus: string | null;
  /** §9.1 mode payload (coding problem, design focus dimension). */
  extra: Record<string, unknown>;
  /** v0.4: question-source attribution (null when generated by the interviewer). */
  source: QuestionCandidate["source"] | null;
};

function parseList<T>(v: unknown): T[] {
  return Array.isArray(v) ? (v as T[]) : JSON.parse(String(v ?? "[]"));
}

function parseObj(v: unknown): Record<string, unknown> | null {
  if (v === null || v === undefined) return null;
  if (typeof v === "object") return v as Record<string, unknown>;
  const s = String(v);
  return s === "" ? null : (JSON.parse(s) as Record<string, unknown>);
}

export function rowToAction(row: {
  id: string;
  skillId: string;
  priority: number;
  reason: string;
  action: string;
  successCriteria: unknown;
  status: string;
  severity?: string;
  createdAt: string;
  sourceEvidenceIds: unknown;
  resources?: unknown;
}): PrepActionRowLike {
  return {
    id: row.id,
    skillId: row.skillId,
    priority: row.priority,
    reason: row.reason,
    action: row.action,
    successCriteria: parseList(row.successCriteria),
    status: row.status,
    severity: row.severity ?? "medium",
    createdAt: row.createdAt,
    sourceEvidenceIds: parseList(row.sourceEvidenceIds),
    resources: parseList(row.resources),
  };
}

export function rowToQuestion(row: {
  id: string;
  sessionId: string;
  skillId: string;
  topic: string;
  text: string;
  subSkills: unknown;
  expectedConcepts: unknown;
  difficulty: string;
  selectionReason?: string | null;
  selectionPriority?: number | null;
  selectionFactors?: unknown;
  followUpOf?: string | null;
  followUpFocus?: string | null;
  extra?: unknown;
  createdAt: string;
}): OrchestratorQuestion {
  const factors = parseObj(row.selectionFactors);
  return {
    id: row.id,
    sessionId: row.sessionId,
    skillId: row.skillId as SkillId,
    topic: row.topic,
    text: row.text,
    subSkills: parseList<string>(row.subSkills) as SkillId[],
    expectedConcepts: parseList(row.expectedConcepts),
    difficulty: row.difficulty as Question["difficulty"],
    selectionReason: row.selectionReason ?? null,
    selectionPriority: row.selectionPriority ?? null,
    selectionFactors:
      factors && Object.keys(factors).length > 0
        ? (factors as Record<string, number>)
        : null,
    followUpOf: row.followUpOf ?? null,
    followUpFocus: row.followUpFocus ?? null,
    extra: parseObj(row.extra) ?? {},
    source: (parseObj(row.extra)?.source as QuestionCandidate["source"]) ?? null,
    createdAt: row.createdAt,
  };
}
